language: python
sudo: false
install:
  - pip install tox
script:
  - tox -r
env:
  - TOXENV=style
  - TOXENV=coverage
  - TOXENV=2to3
  - TOXENV=py2.7-django1.8-unittest
  - TOXENV=py2.7-django1.8-integration
  - TOXENV=py2.7-django1.8-experiments
  - TOXENV=py3.5-django1.8-unittest
  - TOXENV=py3.5-django1.8-integration
  - TOXENV=py3.5-django1.8-experiments
