language: python
sudo: false
# Specify Python 3.5 explicitley. We can still run Python 2.x tests in that
# environment, but Python 3.5 won't be available the other way around.
# See for details: https://github.com/travis-ci/travis-ci/issues/4794
python: 3.5
install:
  - pip install tox
script:
  - tox -r
env:
  - TOXENV=style
  - TOXENV=coverage
  - TOXENV=python3-warnings
  - TOXENV=py2.7-unittest
  - TOXENV=py2.7-integration
  - TOXENV=py2.7-experiments
  - TOXENV=py3.5-unittest
  - TOXENV=py3.5-integration
  - TOXENV=py3.5-experiments
