language: python
env:
  - SCRIPT="python runtests.py"
  - SCRIPT="cd otree-lib && ./otree recreate && ./otree test_all"
python: 2.7
install:
  - python setup.py install

  # Setup integration tests.
  - git clone https://github.com/oTree-org/oTree.git otree-lib
  - virtualenv otree-lib/.env --no-site-packages
  - otree-lib/.env/bin/pip install -r otree-lib/requirements.txt
  - otree-lib/.env/bin/python setup.py install

script:
  - $SCRIPT
